src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/achilles/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import adoffice.urls
import packaging.urls
from . import views
from filebrowser.sites import site
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import patterns
from django.http import HttpResponse

urlpatterns = i18n_patterns(
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^thanks/$', views.SubscriberPage.as_view(), name='subscribed'),
    #url(r'^product/$', views.ProductPage.as_view(), name='product'),
    url(r'^katalog/', include(adoffice.urls, namespace='adoffice')),
    # url(r'^opakowania/', include(packaging.urls, namespace='packaging')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^admin/filebrowser/', include(site.urls)),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)
#urlpatterns += patterns('', url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")))
#(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'))
# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.conf import settings
from django.utils.translation import ugettext_lazy as _


class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True)
    slug = models.UUIDField(default=uuid.uuid4, blank=True, editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    picture = models.ImageField(_('Moje logo'),
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.BooleanField(_("Artykuły Reklamowe"), default=True, blank=True)
    newsp = models.BooleanField(_("Opakowania i materiały POS"), default=True, blank=True)
    newsl = models.BooleanField(_("Usługi dla Poligrafii"), default=True, blank=True)
    email_verified = models.BooleanField(_("Email zweryfikowany"), default=False)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Profile(BaseProfile):
    def __str__(self):
        return "{}'s profile". format(self.user)

src/profiles/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import get_user_model
from . import models

User = get_user_model()


class UserForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('name'),
            )

    class Meta:
        model = User
        fields = ['name']


class ProfileForm(forms.ModelForm):
    subscriptions = unicode(_("Newsletter - Moje subskrypcje"))

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.layout = Layout(
            Field('picture'),
            HTML("<p>"+self.subscriptions+":</p>"),
            Field('bio'),
            Field('newsp'),
            Field('newsl'),
            Submit('update', _('Aktualizuj'), css_class="btn-success"),
            )

    class Meta:
        model = models.Profile
        fields = ['picture', 'bio', 'newsp', 'newsl']

src/profiles/views.py
from __future__ import unicode_literals
from django.views import generic
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages
from braces.views import LoginRequiredMixin
from . import forms
from . import models


class ShowProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/show_profile.html"
    http_method_names = ['get']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            profile = get_object_or_404(models.Profile, slug=slug)
            user = profile.user
        else:
            user = self.request.user

        if user == self.request.user:
            kwargs["editable"] = True
        kwargs["show_user"] = user
        return super(ShowProfile, self).get(request, *args, **kwargs)


class EditProfile(LoginRequiredMixin, generic.TemplateView):
    template_name = "profiles/edit_profile.html"
    http_method_names = ['get', 'post']

    def get(self, request, *args, **kwargs):
        user = self.request.user
        if "user_form" not in kwargs:
            kwargs["user_form"] = forms.UserForm(instance=user)
        if "profile_form" not in kwargs:
            kwargs["profile_form"] = forms.ProfileForm(instance=user.profile)
        return super(EditProfile, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        user = self.request.user
        user_form = forms.UserForm(request.POST, instance=user)
        profile_form = forms.ProfileForm(request.POST,
                                         request.FILES,
                                         instance=user.profile)
        if not (user_form.is_valid() and profile_form.is_valid()):
            messages.error(request, "There was a problem with the form. "
                           "Please check the details.")
            user_form = forms.UserForm(instance=user)
            profile_form = forms.ProfileForm(instance=user.profile)
            return super(EditProfile, self).get(request,
                                                user_form=user_form,
                                                profile_form=profile_form)
        # Both forms are fine. Time to save!
        user_form.save()
        profile = profile_form.save(commit=False)
        profile.user = user
        profile.save()
        messages.success(request, "Zapisano")
        return redirect("profiles:show_self")

src/profiles/templates/profiles/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load thumbnail %}
{% load i18n %}
{% block title %}{{ block.super }}Profile{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div class="container">
  <h1 class="text-primary">{% trans "Edytuj Profil" %} </h1>
  <hr>
  <div class="row">
    <!-- left column -->
    <div class="col-md-3">
      <div class="text-center">
        <img title="profile picture" class="img-circle img-responsive" src="{% thumbnail user.profile.picture|default:'default_profile.png' 140x140 crop %}">
      </div>
    </div>
      
    <!-- edit form column -->
    <div class="col-md-9">
      <h3>{% trans 'Mój profil' %}</h3>
      <form enctype="multipart/form-data" method="post">
	{% crispy user_form %}
	{% crispy profile_form %}
      </form>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <a class="btn btn-default pull-right" href="{% url 'accounts:password-change' %}">{% trans "Zmień hasło" %}</a>
    </div>
  </div>
</div>
{% endblock %}

src/profiles/templates/profiles/show_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% load thumbnail %}
{% load i18n  %}
{% block title %}{{ block.super }} {% trans "Profil" %}{% endblock %}

{% block container %}

<div class="container profile-head">
  <div class="row">
    <div class="col-sm-10">
      <h1>{{ show_user.get_full_name }}</h1>
      {% if editable %}
      <a href="{% url 'profiles:edit_self' %}" class="btn btn-info">{% trans "Edytuj Profil" %}</a>
      {% endif %}
    </div>
    <div class="col-sm-2"><img title="profile picture" class="img-circle img-responsive" src="{% thumbnail show_user.profile.picture|default:'default_profile.png' 140x140 crop %}">
    </div>
  </div>
</div>

<div class="container profile-body">
  <div class="row">
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">Profile</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Email:</strong></span> {{ show_user.email|default:"missing" }}
	  {% if show_user.profile.email_verified %}
	    <span class="glyphicon glyphicon-ok-circle" aria-hidden="true" title="This email address has been verified"></span>
	    <span class="sr-only">Verified</span>
	  {% else %}
	    <span class="glyphicon glyphicon-warning-sign" aria-hidden="true" title="This email address is not verified"></span>
	    <span class="sr-only">Not Verified</span>
	  {% endif %}
	</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined</strong></span> {{ show_user.date_joined }}</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last seen</strong></span> {{ show_user.last_login }}</li>
      </ul>
    </div>
    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-heading">{{ show_user.get_full_name }}'s Profile
	  <a href="{% url 'profiles:show' show_user.profile.slug %}">
	    <span class="glyphicon glyphicon-link" aria-hidden="true" title="Profile permalink"></span>
	    <span class="sr-only">Permalink</span></a> {{ show_user.profile.get_absolute_url }}
	</div>
        <div class="panel-body">
            <h3>{% trans 'Newsletter - Moje subskrybcje' %}</h3>
	  <strong>{% trans 'Artykuły Reklamowe' %}</strong>: {% if show_user.profile.bio == True %} {% trans "Aktywne" %} {% else %} {% trans "Nieaktywne" %}{% endif %}<br/>
            <strong>{% trans 'Opakowania i materiały POS' %} </strong>: {% if show_user.profile.newsp == True %} {% trans "Aktywne" %} {% else %} {% trans "Nieaktywne" %}{% endif %} <br/>
            <strong>{%  trans 'Usługi dla Poligrafii' %} </strong>: {% if show_user.profile.newsl == True %} {% trans "Aktywne" %} {% else %} {% trans "Nieaktywne" %}{% endif %}

	</div>
      </div>
    </div>
</div>

{% endblock %}