src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/achilles/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import adoffice.urls
import packaging.urls
from . import views
from filebrowser.sites import site
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import patterns
from django.http import HttpResponse

urlpatterns = i18n_patterns(
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^thanks/$', views.SubscriberPage.as_view(), name='subscribed'),
    #url(r'^product/$', views.ProductPage.as_view(), name='product'),
    url(r'^katalog/', include(adoffice.urls, namespace='adoffice')),
    # url(r'^opakowania/', include(packaging.urls, namespace='packaging')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^admin/filebrowser/', include(site.urls)),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)
#urlpatterns += patterns('', url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")))
#(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'))
# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>[\w\-]+)$', views.ShowProfile.as_view(),
        name='show'),
]

src/templates/_brandname.html
Achilles <span class="achilles">Polska.</span>

src/templates/_navbar.html
{% load i18n %}
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Start</a></li>
<li {% if active_link == "about" %}class="active"{% endif %}><a href="{% url 'about' %}">{% trans "O Nas" %}</a></li>
<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Oferta" %} <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/#office">{% trans "Artykuły Reklamowe" %}</a></li>
            <li><a href="/#packaging">{% trans "Opakowania i materiały POS" %}</a></li>
            <li><a href="/#laminating">{% trans "Usługi dla Poligrafii" %}</a></li>

          </ul>
        </li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{{ block.super }}{{ page.title }}{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}
{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">{% trans "Zaloguj" %}</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">{% trans "Zarejestruj się" %}</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}
<!-- Benefits of the Django application -->
{% block container %}

<div id="achilles" class="text-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1> </h1>
        <p class="lead"></p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  {{ page.section1|safe }}
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Kontakt</h2>
          <address>
            <strong>Achilles Polska</strong><br>
            ul. M. Płażyńskiego 6 <br>83-020 Cedry Wielkie
            <section >
              <p>
                  <i class="fa fa-phone"></i> (58) 683 60 30 <br/>
                  <i class="fa fa-envelope"></i> achilles@achilles.pl
              </p>
            </section>
          </address>
            Spółka zarejestrowana w rejestrze Krajowego Rejestru Sądowego prowadzonego przez Sąd Rejonowy Gdańsk-Północ w Gdańsku VII Wydział Gospodarczy Krajowego Rejestru Sądowego, KRS 0000000622.
NIP: 583-27-15-203. Kapitał zakładowy: 2.280.000 PLN
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(54.24436,18.84061);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
 {% load i18n %}

{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
    {% load staticfiles %}
    {% load thumbnail %}

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Krzysztof Olszewski">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}Achilles Polska. Artykuły Reklamowe, Opakowania i Uszlachetnianie Druku :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}
    <script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              {#<img src="{% static 'site/img/logo.png' %}" alt="logo">#}
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
          <li><span class="navbar-phone"><i class="fa fa-phone"></i> +48 58 683 60 30</span></li>
          <li><span class="navbar-phone"><i class="fa fa-envelope"></i> achilles@achilles.pl</span></li>
                <li><a href="/pl"><img src="{% static '/static/site/img/pl.png' %}"/></a></li>
                <li><a href="/en"><img src="{% static '/static/site/img/en.png' %}"/></a></li>
            {% block navbar-right %}

              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">{% trans "Profil" %}</a></li>
                    <li><a href="{% url 'accounts:logout' %}">{% trans "Wyloguj się" %}</a></li>
                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </nav>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Achilles Polska {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            <address>
            <strong>Achilles Polska</strong><br>
            ul. M. Płażyńskiego 6 <br>83-020 Cedry Wielkie
            <section>
              <p>
                  <i class="fa fa-phone"></i> (58) 683 60 30 <br/>
                  <i class="fa fa-envelope"></i> achilles@achilles.pl
              </p>
            </section>
          </address>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    {% include "fm/modal.html" %}
    {% block scripts %}

    {% endblock scripts %}

  </body>
</html>

src/templates/contact.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}{{ page.title }}{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1> </h1>
        <p class="lead"></p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  {{ page.section1|safe }}
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Kontakt</h2>
          <address>
            <strong>Achilles Polska</strong><br>
            ul. M. Płażyńskiego 6 <br>83-020 Cedry Wielkie
            <section >
              <p>
                  <i class="fa fa-phone"></i> (58) 683 60 30 <br/>
                  <i class="fa fa-envelope"></i> achilles@achilles.pl
              </p>
            </section>
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(54.24436,18.84061);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/product_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Product Page{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}



<div id="sec2" class="text-page">
  <div class="container-fluid">
    <div class="row">
       <div class="col-lg-3">
                <h3>Segregator Reklamowy</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
                <table class="striped">
 <tbody>
              <tr>
                <td>
                  Format:
                </td>
                <td>
                  A4.
                </td>
              </tr>
              <tr>
                <td>
                  Mechanizmy:
                </td>
                <td>
                  Dźwigniowe, 2-ringowe, 4-ringowe.
                </td>

              </tr>
            <tr>
                <td>
                Dodatki:
                </td>
                <td>
                  Kółko grzbietowe, Oczka Rado, Kieszonka grzbietowa, Kieszonka trójkątna, Kieszonka na wizytówkę, Kieszonka na płytę dvd.
                </td>
            </tr>
            <tr>
              <td>
                Uszlachetnienie:&nbsp;
              </td>
              <td>
                Folia błyszcząca, matowa, matowa nierysująca, folia o strukturze lnu.
              </td>
            </tr>
            </tbody>
            </table>
            <div class="product-nav">
               <a href="" id="product-prev"><-</a>
                <div class="product-gallery"></div>
               <a href="" id="product-next">-></a>
            </div>
            </div>
<div class="col-lg-9">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                    <div class="carousel-inner">
                        <div class="item active">
                            <img class="img-responsive" src="http://placehold.it/1400x750" alt="">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="http://placehold.it/1400x750" alt="">
                        </div>
                        <div class="item">
                            <img class="img-responsive" src="http://placehold.it/1400x750" alt="">
                        </div>
                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>
    </div>
    </div>
  </div>
</div>


{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(54.24436,18.84061);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/subscribed.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{{ block.super }}{{ page.title }}{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="subscribed" class="text-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1> </h1>
        <p class="lead"></p>
      </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
    <div id="mainquote">
      {% trans "Dziękujemy za zapisanie się do naszej listy subskrybentów. Sprawdź swoją pocztę email." %}</div>
    </div>
  </div>
</div>
{% endblock container %}