src/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),  # NOQA
        name='password-reset-confirm'),
]

src/achilles/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
import adoffice.urls
import packaging.urls
from . import views
from filebrowser.sites import site
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls import patterns
from django.http import HttpResponse

urlpatterns = i18n_patterns(
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^thanks/$', views.SubscriberPage.as_view(), name='subscribed'),
    #url(r'^product/$', views.ProductPage.as_view(), name='product'),
    url(r'^katalog/', include(adoffice.urls, namespace='adoffice')),
    # url(r'^opakowania/', include(packaging.urls, namespace='packaging')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^admin/filebrowser/', include(site.urls)),
    #url(r'^i18n/', include('django.conf.urls.i18n')),
)
#urlpatterns += patterns('', url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")))
#(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain'))
# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/packaging/urls.py
__author__ = 'ko'
from django.conf.urls import url
from . import views
from .models import Category, Product

urlpatterns = [
    url(r'^(?P<category>[\w-]+)/(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(model=Product), name='product'),
    url(r'^(?P<slug>[\w-]+)/$', views.CategoryDetail.as_view(model=Category), name='detail'),
    url(r'^test/create/1/$', views.TestView.as_view(), name='test'),
    ]

src/adoffice/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.html import strip_tags
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext, ugettext_lazy as _
from filebrowser.fields import FileBrowseField
from django.core.mail import send_mail
# Create your models here.


class MetaData(models.Model):
    """
    Abstract model that provides meta data for content.
    """

    _meta_title = models.CharField(_(u"Tytuł sekcji meta"), null=True, blank=True,
                                   max_length=500, help_text=_(u"Opcjonalny HTML title tag."))
    meta_description = models.TextField(_(u"Opis sekcji meta"), blank=True)
    keywords = models.CharField(max_length=500, blank=True, null=True)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        """
        Set the description field on save.
        """
        self.meta_description = strip_tags(self.meta_description)
        super(MetaData, self).save(*args, **kwargs)

    def meta_title(self):
        """
        Accessor for the optional ``_meta_title`` field, which returns
        the string version of the instance if not provided.
        """
        return self._meta_title or str(self)


class Segment(models.Model):
    title = models.CharField(max_length=254)

    def __unicode__(self):
        return self.title

#class Page(models.Model):


class Category(MetaData):

    slug = models.SlugField(max_length=50)
    title = models.CharField(_(u'Tytuł'), default='', max_length=254, blank=False, null=False)
    items_title = models.CharField(_(u'Tytuł Katalogu'), default='', max_length=254, blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    slogan = models.CharField(max_length=255, default='', blank=True)
    description = models.TextField(_(u'Opis'), blank=True, null=True)
    picture = models.ImageField(_(u'Kategoria'), default='pics/default.png', upload_to='pics/',
                                blank=False, null=False)
    header = models.CharField(_(u'Klasa obrazka'), max_length=50, default='sec1', blank=True, null=True)
    order = models.IntegerField(default=0, blank=False, null=False)
    parent_category = models.ForeignKey('self', blank=True, null=True, related_name="subcategories")
    segment = models.ForeignKey(Segment, default='1', blank=False, null=False)

    #products = models.ManyToManyField(Product, blank=True, null=True)

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("adoffice:detail", kwargs={"slug": self.slug})


class PageClass(models.Model):
    name = models.CharField(max_length=255, default='homepage', blank=False, null=False)

    def __unicode__(self):
        return self.name


class Page(MetaData):
    section1 = models.TextField(u'Sekcja-1', blank=True, null=True)
    section2 = models.TextField(u'Sekcja-2', blank=True, null=True)
    title = models.CharField(max_length=254, default='')
    pageclass = models.ForeignKey(PageClass, default='1', blank=False, null=False)

    def __unicode__(self):
        return self.title


#subcategories = Category.objects.filter(parent_category__id=target_category.id)


class GroupCategory(models.Model):
    title = models.CharField(max_length=254)

    def __unicode__(self):
        return self.title


class Finishing(models.Model):
    title = models.CharField(max_length=254)

    def __unicode__(self):
        return self.title


class Accessories(models.Model):
    title = models.CharField(max_length=254)

    def __unicode__(self):
        return self.title


class Product(MetaData):
    _category = ''
    title = models.CharField(max_length=254)
    slug = models.SlugField(max_length=150, unique=True)
    description = models.TextField(_(u'Opis'), blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    format_size = models.CharField(max_length=25, blank=True)
    category = models.ManyToManyField(Category, blank=True, null=True, name='categories')
    group_category = models.ManyToManyField(GroupCategory, blank=True, null=True)
    finishing = models.ManyToManyField(Finishing, blank=True, null=True)
    accessories = models.ManyToManyField(Accessories, blank=True, null=True)
    picture = models.ImageField(_(u'Obrazek'), default='pics/default.png', upload_to='pics/',
                                blank=False, null=False)
    document = FileBrowseField("PDF", max_length=200, directory="documents/", extensions=[".pdf"], blank=True, null=True)

    def __unicode__(self):
        return self.title

    class Meta:
        unique_together = ('title', 'slug')

    def get_absolute_url(self):
        return reverse("adoffice:product", kwargs={"slug": self.slug, "category": self.categories.all()[0].slug})

    def get_next(self):
            self._category = self.categories.all()[0]
            next = Product.objects.filter(id__gt=self.id, categories__in=[self._category], active=True).order_by('id')
            if next:
                return next[0]
            return False

    def get_prev(self):
        self._category = self.categories.all()[0]
        prev = Product.objects.filter(id__lt=self.id, categories__in=[self._category], active=True).order_by('-id')
        if prev:
            return prev[0]
        return False

    def get_category(self):
        self._category = self.categories.all()[0]
        return self._category


class ProductImage(models.Model):
    product = models.ForeignKey(Product)
    picture = models.ImageField(_(u'Obrazek'), default='pics/default.png', upload_to='pics/',
                                blank=False, null=False)
    featured = models.BooleanField(default=False)
    thumbnail = models.BooleanField(default=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __unicode__(self):
        return self.product.title


class Quota(models.Model):
    email = models.EmailField()
    ref = models.CharField(max_length=254, default='')
    full_name = models.CharField(_(u'Imię i Nazwisko'), max_length=254, default='', blank=False, null=False)
    company = models.CharField(_(u'Firma'), max_length=254, default='', blank=True, null=True)
    phone = models.CharField(_(u'Telefon'), max_length=254, default='')
    note = models.TextField(_(u'Wiadomość'), default='', blank=True, null=True)
    newsletter = models.BooleanField(_(u'Newsletter'), default=True, help_text=_(u'Chcę być informowany o nowościach i ofertach firmy Achilles.'))
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __unicode__(self):
        return self.email

    def save(self):
        if self.email:
            message = _("Zapytanie strona www ").format(self)
            subject = _(u"Dziękujemy za kontakt")
            #send_mail(subject, message, "no-replay@achilles.pl", [self.email, ])
            #print('Stored: {}'.format(self))
        super(Quota, self).save()

src/adoffice/forms.py
from __future__ import unicode_literals
from django import forms
from .models import Quota
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field
from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.contrib.auth import get_user_model


# Quota is stored in database
class SignUpForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout.append(
            Submit('submit', 'Zamawiam',
                   css_class="btn btn-lg btn-primary btn-block"),
            )

    class Meta:
        model = Quota
        fields = ['email', 'full_name', 'company', 'phone', 'note', 'newsletter']

src/adoffice/views.py
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from .models import Category, Product, ProductImage
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from fm.views import AjaxCreateView
from .forms import SignUpForm


class CategoryDetail(SingleObjectMixin, ListView):
    paginate_by = 2
    template_name = "category_detail.html"

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Category.objects.all())
        return super(CategoryDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CategoryDetail, self).get_context_data(**kwargs)
        context['category'] = self.object
        context['product_list'] = Product.objects.filter(categories=self.object, active=True).order_by('id')
        return context


class ProductDetailView(DetailView):
    template_name = "product_detail.html"
    model = Product

    #context_object_name = 'product'
    #def get(self, request, *args, **kwargs):
    #    self.object = self.get_object(queryset=Product.objects.all())
    #    return super(ProductDetailView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['product_images'] = ProductImage.objects.filter(product=self.get_object())
        context['product_segment'] = self.get_object().categories.all()[0].segment
        context['category'] = self.get_object().get_category()
        return context


class TestView(AjaxCreateView):
    form_class = SignUpForm


def add_quote(request):
    # Get the context from the request.
    context = RequestContext(request)

    # A HTTP POST?
    if request.method == 'POST':
        form = SignUpForm(request.POST or None)

        # Have we been provided with a valid form?
        if form.is_valid():
            # Save the new category to the database.
            form.save(commit=True)
            #post_save.connect(send_update, sender=Book)
            # Now call the index() view.
            # The user will be shown the homepage.
            return redirect('/thanks/')
        else:
            # The supplied form contained errors - just print them to the terminal.
            print form.errors
    else:
        # If the request was not a POST, display the form to enter details.
        form = SignUpForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render_to_response('add_signup.html', {'form': form}, context)


class ThanksPage(TemplateView):
    template_name = "thanks.html"

src/adoffice/templates/_product_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Product Page{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec2" class="product-page">
  <div class="container-fluid">
    <div class="row">
       <div class="col-lg-3">
                <h3>{{ product.title }}</h3>
                <p>{{ product.description|safe }}</p>
           {% if product_segment.title == 'biuro' or '' %}
           <table class="striped">
 <tbody>
              <tr>
                <td>
                  Format:
                </td>
                <td>
                  {{ product.format_size }}
                </td>
              </tr>
              <tr>
                <td>
                  Rodzaj:
                </td>
                <td>
                    {% for g in product.group_category.all  %}
                      {{ g.title }}, &nbsp;
                    {% endfor %}
                </td>

              </tr>
            <tr>
                <td>
                Dodatki:
                </td>
                <td>
                  {% for a in product.accessories.all %}
                      {{ a.title }}, &nbsp;
                    {% endfor %}
                </td>
            </tr>
            <tr>
              <td>
                Uszlachetnienie:&nbsp;
              </td>
              <td>
               {% for f in product.finishing.all  %}
                      {{ f.title }} &nbsp;
                    {% endfor %}
              </td>
            </tr>
            </tbody>
            </table>{% endif %}
<a href="{% url 'adoffice:test' %}" class="fm-create btn btn-primary" data-fm-target="#msg-info" data-fm-head="{% trans "Wyślij zapytanie" %}-{{ product.title }}" data-fm-callback="replace">{% trans "Wyślij zapytanie" %}</a>
           <div id="msg-info" class="alert alert-info">
          {% trans "Dziękujemy za kontakt, wkrótce skontaktuje się z Tobą nasz przedstawiciel." %}
           </div>
           <div class="product-nav">
               <a href="{{ product.get_prev.get_absolute_url }}" id="product-prev"><-</a>
                <div class="product-gallery"></div>
               <a href="{{ product.get_next.get_absolute_url }}" id="product-next">-></a>
            </div>
            </div>
<div class="col-lg-9">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides produkt -->
                    <div class="carousel-inner">
                    {% if product_images %}
                        {% for p in product_images %}

                        <div class="item {% if forloop.first %}active{% endif %}">

                            <img class="img-responsive" src="{% static p.picture.url %}" alt="">
                        </div>
                    {% endfor %}
                    {% endif %}


                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>
    </div>
    </div>
  </div>
</div>


{% endblock container %}

{% block scripts %}
     <script>
        $(function() {
            $.fm({debug: true});
        });
        </script>
{% endblock scripts %}

src/adoffice/templates/category_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
    {% include "_navbar.html" %}
{% endblock %}
{% block navbar-right %}
  {% if not user.is_authenticated %}
{#<li><a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">{% trans "Zaloguj" %}</a></li>#}
{#<li><a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">{% trans "Zarejestruj się" %}</a></li>#}
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}
<!-- Benefits of the Django application -->
{% block container %}

<div id="{{ category.header }}" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>&nbsp;</h1>
        <p class="lead">&nbsp;</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>{{ category.title }}</h2>
        <p class="lead">

         </p>
      </div>
    </div>

    </div>
  </div>
    <section class="services-section" id="section-1">

      <div class="container">

        <div class="row">
            <div class="panel text-left text-panel">

                {{ category.description|safe }}

            </div>
        </div>
      </div>
    </section>
<section class="office-section">
<div class="container">
<h2>{% if category.items_title %} {{ category.items_title }} {% else %}{% trans "Przykładowe realizacje" %}{% endif %}</h2>
<!-- Projects Row -->

{% if product_list %}
        {% for p in product_list %}
            {% if forloop.counter0|divisibleby:4 %}
                <div class="row">
            {% endif %}

            <div class="col-md-3 portfolio-item item-thumbs">
                <a href="{{ p.slug }}">
                    <img class="img-responsive" src="{{ p.picture.url }}" alt="">
                </a>
                <h3>
                    <a href="{{ p.slug }}">{{ p.title }}</a>
                </h3>
            </div>
            {% if forloop.counter|divisibleby:4 %}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    </div>
</section>
</div>

{% endblock container %}

{% block scripts %}
{% endblock scripts %}

src/adoffice/templates/product_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Product Page{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec2" class="text-page">
  <div class="container-fluid">
    <div class="row">
       <div class="col-lg-3">
       <div id="product-description">
                <h3>{{ product.title }}</h3>
                <p>{{ product.description|safe }}</p>
           {% if product_segment.title == 'biuro' or '' %}
           <table class="striped">
            <tbody> {% if product.format_size %}
              <tr>
                <td>
                  {% trans "Format" %}:
                </td>
                <td>
                  {{ product.format_size }}
                </td>
              </tr>{% endif %} {% if product.group_category.all %}
              <tr>
                <td>
                  {% trans "Rodzaj" %}:
                </td>
                <td>
                    {% for g in product.group_category.all  %}
                      {{ g.title }}, &nbsp;
                    {% endfor %}
                </td>

              </tr>{% endif %} {% if product.accessories.all %}
            <tr>
                <td>
                {% trans "Dodatki" %}:
                </td>
                <td>
                  {% for a in product.accessories.all %}
                      {{ a.title }}, &nbsp;
                    {% endfor %}
                </td>
            </tr>{% endif %} {% if product.finishing.all %}
            <tr>
              <td>
                {%  trans "Uszlachetnienie" %}:&nbsp;
              </td>
              <td>
               {% for f in product.finishing.all  %}
                      {{ f.title }} &nbsp;
                    {% endfor %}
              </td>
            </tr>{% endif %}
            </tbody>
            </table>
           {% if product.document.url %}
               <p>Szablon PDF: &nbsp;<a href="{{ product.document.url }}" target="_blank"><i class="fa fa-file-pdf-o"></i></a></p>
           {% endif %}{% endif %}
       <div id="msg-info" class="alert alert-info">
          {% trans "Dziękujemy za kontakt, wkrótce skontaktuje się z Tobą nasz przedstawiciel." %}
           </div>
       </div>
           <a href="{% url 'adoffice:test' %}" class="fm-create btn btn-primary" data-fm-target="#msg-info" data-fm-head="{% trans "Wyślij zapytanie" %}-{{ product.title }}" data-fm-callback="replace">{% trans "Wyślij zapytanie" %}</a>

           <div class="product-navigation visible-lg hidden-xs hidden-sm hidden-md">
                    <div class="product-nav">
                       <a class="glyphicon glyphicon-chevron-left" href="{{ product.get_prev.get_absolute_url }}" id="product-prev"></a>
                        <a class="glyphicon glyphicon-th-large" href="{{ category.get_absolute_url }}" title="{% trans 'Powrót do katalogu'%}"></a>
                        <!--<div class="product-gallery"></div>-->
                       <a class="glyphicon glyphicon-chevron-right" href="{{ product.get_next.get_absolute_url }}" id="product-next"></a>
                    </div>
               </div>
       </div>
        <div class="col-lg-9">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                    </ol>

                    <!-- Wrapper for slides produkt -->
                    <div class="carousel-inner">
                    {% if product_images %}
                        {% for p in product_images %}

                        <div class="item {% if forloop.first %}active{% endif %}">

                            <img class="img-responsive" src="{% static p.picture.url %}" alt="">
                        </div>
                    {% endfor %}
                    {% endif %}


                    </div>

                    <!-- Controls -->
                    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>
                </div>
            </div>

        <div class="product-navigation col-lg-3 hidden-lg">
            <div class="product-nav">
                <a class="glyphicon glyphicon-chevron-left" href="{{ product.get_prev.get_absolute_url }}" id="product-prev"></a>
                <a href="{{ product.get_absolute_url}}"><span class="glyphicon glyphicon-th-large"></span></a>
                <!--<div class="product-gallery"></div>-->
                <a class="glyphicon glyphicon-chevron-right" href="{{ product.get_next.get_absolute_url }}" id="product-next"></a>
            </div>
        </div>

    </div>
    </div>
  </div>
</div>


{% endblock container %}

{% block scripts %}
     <script>
        $(function() {
            $.fm({debug: true});
        });
        </script>
{% endblock scripts %}